# 可选：本地开发覆盖文件示例
version: "3.9"
services:
  app:
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
