version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: puzzle-temp-api:latest
    container_name: puzzle-temp-api
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
